In [1]:
import pandas as pd
from numpy import *
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
#severity 1 data
gyr = pd.read_csv("/home/tanay/Downloads/temp_val.csv", header =None)
acc =pd.read_csv("/home/tanay/Downloads/accel_values.csv", header = None)

In [3]:
gyr.columns = ["time","z","runId","turnId","aggresive"]


In [4]:
gyr = gyr.fillna(999)

In [5]:
gyr["z"] = gyr["z"].rolling(20).mean()[20:]

In [6]:
gyr.head(30)

time         z  runId  turnId  aggresive
0   1408346730004       NaN      1      23          0
1   1408346730055       NaN      1      23          0
2   1408346730106       NaN      1      23          0
3   1408346730155       NaN      1      23          0
4   1408346730205       NaN      1      23          0
5   1408346730254       NaN      1      23          0
6   1408346730305       NaN      1      23          0
7   1408346730354       NaN      1      23          0
8   1408346730404       NaN      1      23          0
9   1408346730455       NaN      1      23          0
10  1408346730505       NaN      1      23          0
11  1408346730555       NaN      1      23          0
12  1408346730604       NaN      1      23          0
13  1408346730655       NaN      1      23          0
14  1408346730708       NaN      1      23          0
15  1408346730754       NaN      1      23          0
16  1408346730804       NaN      1      23          0
17  1408346730854       NaN      1      23          0
18  1408346730906       NaN      1      23          0
19  1408346730956       NaN      1      23          0
20  1408346731005  0.004848      1      23          0
21  1408346731055  0.006662      1      23          0
22  1408346731104  0.008550      1      23          0
23  1408346731155  0.010367      1      23          0
24  1408346731204  0.011929      1      23          0
25  1408346731255  0.013132      1      23          0
26  1408346731306  0.014144      1      23          0
27  1408346731355  0.014963      1      23          0
28  1408346731405  0.015670      1      23          0
29  1408346731454  0.016534      1      23          0

In [7]:
gyr=gyr[gyr.aggresive==0]

In [8]:
gyr.turnId.unique()

array([23, 24, 27, 30, 32, 34, 40, 41, 46, 47, 52, 57, 60, 61, 62, 63, 22,
       25])

In [9]:
df= gyr.groupby("turnId")

In [24]:
run4= df.get_group(61)
t = run4.groupby("runId")

In [25]:
run4.runId.unique()

array([1, 3, 4, 5, 6, 7, 8, 9])

In [27]:
fig = make_subplots(rows=1, cols=1)
fig.append_trace(go.Scatter(y=t.get_group(1).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(3).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(4).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(5).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(8).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(7).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(6).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(9).z.values), row=1, col=1)
fig.show()

In [28]:
t.get_group(7).z.values.shape

(239,)

In [29]:
sum2 = np.zeros(239)
for i in [1,3,4,5,6,7,8,9]:
    sum2 = sum2+ t.get_group(i).z.values[:239]
sum2 = sum2/6

Template for bend severity #2

In [30]:
fig = make_subplots(rows=1, cols=1)
fig.append_trace(go.Scatter(y=sum2), row=1, col=1)
fig.show()

In [31]:
#severity 2 data
gyr3 = pd.read_csv("/home/tanay/Downloads/temp2_val.csv", header =None)
gyr3.columns = ["time","z","runId","turnId","aggresive"]

In [32]:
gyr3["z"] = gyr3["z"].rolling(20).mean()[20:]

In [33]:
gyr3=gyr3[gyr3.aggresive==0]

In [34]:
gyr3.turnId.unique()

array([77,  4,  6,  8, 13, 17, 10])

In [35]:
df= gyr3.groupby("turnId")
run4= df.get_group(4)
t = run4.groupby("runId")
run4.runId.unique()

array([2, 3, 4, 5, 8, 9])

In [36]:
fig = make_subplots(rows=1, cols=1)
fig.append_trace(go.Scatter(y=t.get_group(2).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(3).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(5).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(4).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(8).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(9).z.values), row=1, col=1)
fig.show()

In [37]:
temp3 = np.zeros(135)
for i in [2, 3, 4, 5, 8, 9]:
    temp3 = temp3+ t.get_group(i).z.values[:135]
temp3 = temp3/6

Template For bend Severity #3

In [38]:
fig = make_subplots(rows=1, cols=1)
fig.append_trace(go.Scatter(y=temp3), row=1, col=1)
fig.show()

In [84]:
#severity 3 data
gyr2 = pd.read_csv("/home/tanay/Downloads/temp3_vals.csv", header =None)
gyr2.columns = ["time","z","runId","turnId","aggresive"]
gyr2["z"] = gyr2["z"].rolling(20).mean()[20:]

In [85]:
gyr2=gyr2[gyr2.aggresive==1]

In [87]:
gyr2.turnId.unique()

array([35, 45, 49, 50, 12, 14, 29, 37, 39, 42, 51, 53, 59, 55, 56, 54, 68,
       71, 33, 36])

In [90]:
df= gyr2.groupby("turnId")
run4= df.get_group(33)
t = run4.groupby("runId")
run4.runId.unique()

array([7])

In [91]:
fig = make_subplots(rows=1, cols=1)
fig.append_trace(go.Scatter(y=t.get_group(3).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(8).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(5).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(2).z.values), row=1, col=1)
fig.append_trace(go.Scatter(y=t.get_group(9).z.values), row=1, col=1)
fig.show()

In [82]:
temp2 = np.zeros(266)
for i in [2, 3, 5, 6, 8, 9]:
    temp2 = temp2+ t.get_group(i).z.values[:266]
temp2 = temp2/6

Template for bend severity #2

In [83]:
fig = make_subplots(rows=1, cols=1)
fig.append_trace(go.Scatter(y=temp2), row=1, col=1)
fig.show()